package io.amscotti.janus.core.codec;

import static org.junit.jupiter.api.Assertions.assertEquals;

import io.amscotti.janus.core.model.ChatRequest;
import io.amscotti.janus.core.model.ChatResponse;
import io.amscotti.janus.core.model.StreamChunk;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import org.junit.jupiter.api.Tag;
import org.junit.jupiter.api.Test;

/**
 * offline corpus generator — {@code @Tag("capture")} so it never runs in the default
 * CI test task, but <b>network-free</b>: it reads the committed upstream-shaped fixtures
 * ( {@code openai/} corpus, the {@code anthropic/} corpus, the hand-authored
 * tools upstream legs) and re-derives every Janus-generated leg through the two codecs.
 * Running {@code./gradlew :janus-core:captureFixtures} regenerates the committed corpus
 * in place — {@code GoldenMatrixTest} then asserts the regenerated bytes are identical,
 * so a codec change that alters wire bytes fails CI (and the corpus is machine-
 * reproducible in one command, the capture-harness precedent).
 *
 * <p><b>What is emitted.</b>
 *
 * <ul>
 * <li>{@code fixtures/matrix/canonical/*} — the canonical request records from
 * {@link MatrixCanonicals}, the canonical responses derived from the upstream
 * fixtures, and the canonical stream chunk array — byte-golden under
 * {@link JsonSupport#mapper} serialization (the single source the golden and
 * property suites read);
 * <li>{@code fixtures/matrix/{oo,oa,ao,aa}/{plain,tools,stream}/*} — per cell:
 * {@code inbound.request.json} (face codec), {@code outbound.request.json} (upstream
 * codec), {@code outbound.response.json}/{@code outbound.stream.sse} (face codec),
 * plus verbatim copies of the upstream legs from the corpora where shapes match;
 * <li>{@code fixtures/anthropic/chat.request.json} +
 * {@code chat.request.stream.json} — the byte-golden corpus request fixtures
 * (Anthropic codec output; the {@code anthropic/} corpus mirror of 's
 * {@code openai/} request fixtures).
 * </ul>
 *
 * <p><b>Invariants checked here</b> (fail-fast so a drift surfaces at regeneration time,
 * not silently): the stream corpus decodes to exactly {@link
 * MatrixCanonicals#streamChunks}; the anthropic corpus response decodes to the
 * same conversation as the response (modulo the documented Anthropic format fields).
 */
@Tag("capture")
class MatrixFixtureGeneratorTest {

    private static final Path FIXTURES =
            Path.of(System.getProperty("user.dir"), "src", "test", "resources", "fixtures");
    private static final Path MATRIX = FIXTURES.resolve("matrix");
    private static final Path ANTHROPIC = FIXTURES.resolve("anthropic");

    /** Direction pairs: {@code oo} {@code oa} {@code ao} {@code aa} (face × upstream). */
    private static final List<String> DIRS = List.of("oo", "oa", "ao", "aa");

    private static final List<String> MODES = List.of("plain", "tools", "stream");

    private final OpenAiMessageCodec openAi = new OpenAiMessageCodec(JsonSupport.mapper());
    private final AnthropicMessageCodec anthropic = new AnthropicMessageCodec(JsonSupport.mapper());

    @Test
    void regenerateMatrixCorpus() throws Exception {
        // Upstream-shaped fixtures the generator reads (never re-derived — the C1
        // discipline: the corpus pins the upstream's bytes, the tests pin the codec's).
        String openAiPlainResponse = readResource("/fixtures/openai/chat.response.json");
        String openAiStream = readResource("/fixtures/openai/chat.stream.sse");
        String anthropicPlainResponse = readResource("/fixtures/anthropic/chat.response.json");
        String anthropicStream = readResource("/fixtures/anthropic/chat.stream.sse");
        String openAiToolsResponse = readResource("/fixtures/matrix/oo/tools/upstream.response.json");
        String anthropicToolsResponse = readResource("/fixtures/matrix/oa/tools/upstream.response.json");

        // Canonical responses: decode the OpenAI-shaped upstream legs (the reference).
        ChatResponse plainResponse = openAi.decodeResponse(openAiPlainResponse);
        ChatResponse toolsResponse = openAi.decodeResponse(openAiToolsResponse);
        List<StreamChunk> chunks = MatrixCanonicals.streamChunks();

        // Invariant: the stream corpus must decode to exactly the canonical chunks.
        List<String> payloads = SseTestFrames.dataPayloads(openAiStream);
        assertEquals("[DONE]", payloads.get(payloads.size() - 1), "openai corpus must terminate with [DONE]");
        List<StreamChunk> decodedCorpus = payloads.subList(0, payloads.size() - 1).stream()
                .map(openAi::decodeChunk)
                .toList();
        assertEquals(chunks, decodedCorpus, "the stream corpus must decode to the canonical chunks");

        // Invariant: the anthropic corpus response decodes to the same conversation as the
        // OpenAI-shaped one (modulo the documented Anthropic format fields).
        ChatResponse anthropicDecoded = anthropic.decodeResponse(anthropicPlainResponse);
        assertEquals(plainResponse.choices(), anthropicDecoded.choices(), "choices must match across formats");
        assertEquals(plainResponse.usage(), anthropicDecoded.usage(), "usage must match across formats");
        assertEquals(plainResponse.stopReason(), anthropicDecoded.stopReason(), "stop reason must match");
        assertEquals(plainResponse.model(), anthropicDecoded.model(), "model must match");

        // Canonical artifacts (byte-golden under the mapper).
        write(
                MATRIX.resolve("canonical"),
                "plain.request.json",
                JsonSupport.mapper().writeValueAsString(MatrixCanonicals.plainRequest()));
        write(
                MATRIX.resolve("canonical"),
                "tools.request.json",
                JsonSupport.mapper().writeValueAsString(MatrixCanonicals.toolsRequest()));
        write(
                MATRIX.resolve("canonical"),
                "stream.request.json",
                JsonSupport.mapper().writeValueAsString(MatrixCanonicals.streamRequest()));
        write(
                MATRIX.resolve("canonical"),
                "plain.response.json",
                JsonSupport.mapper().writeValueAsString(plainResponse));
        write(
                MATRIX.resolve("canonical"),
                "tools.response.json",
                JsonSupport.mapper().writeValueAsString(toolsResponse));
        write(
                MATRIX.resolve("canonical"),
                "stream.chunks.json",
                JsonSupport.mapper().writeValueAsString(chunks));

        // ---- the ro/ra legs (Responses face × both upstream families) --------------
        // Inbound: hand-authored Responses wire (the C1 discipline — the corpus pins
        // the CLIENT bytes too on this face, since the Responses codec is decode-only
        // for requests). Upstream + outbound.request: byte-copies of the oo/oa cells
        // (same canonical, same upstream codec — the matrix's cross-face proof).
        // Outbound response/stream: the Responses face's encode.
        OpenAiResponsesCodec responses = OpenAiResponsesCodec.create();
        java.util.function.LongSupplier matrixClock = () -> MatrixCanonicals.CREATED * 1000L;
        for (String rDir : java.util.List.of("ro", "ra")) {
            String sibling = rDir.equals("ro") ? "oo" : "oa";
            for (String mode : MODES) {
                Path cell = MATRIX.resolve(rDir).resolve(mode);
                write(cell, "inbound.request.json", responsesInbound(mode));
                // same canonical → same upstream encode: byte-copy the sibling's
                // outbound REQUEST leg (the cross-face proof), and its upstream legs.
                copy(
                        MATRIX.resolve(sibling).resolve(mode).resolve("outbound.request.json"),
                        cell.resolve("outbound.request.json"));
                copy(MATRIX.resolve(sibling).resolve(mode).resolve(inFile(mode)), cell.resolve(inFile(mode)));
                if (mode.equals("stream")) {
                    OpenAiResponsesCodec.OpenAiResponsesStreamEncoder encoder =
                            responses.newStreamEncoder(MatrixCanonicals.streamRequest(), matrixClock);
                    StringBuilder sse = new StringBuilder();
                    for (var event : encoder.initialEvents()) {
                        sse.append("event: ")
                                .append(event.event())
                                .append('\n')
                                .append("data: ")
                                .append(event.dataJson())
                                .append("\n\n");
                    }
                    for (StreamChunk chunk : chunks) {
                        for (var event : encoder.feed(chunk)) {
                            sse.append("event: ")
                                    .append(event.event())
                                    .append('\n')
                                    .append("data: ")
                                    .append(event.dataJson())
                                    .append("\n\n");
                        }
                    }
                    for (var event : encoder.finish()) {
                        sse.append("event: ")
                                .append(event.event())
                                .append('\n')
                                .append("data: ")
                                .append(event.dataJson())
                                .append("\n\n");
                    }
                    write(cell, "outbound.stream.sse", sse.toString());
                } else {
                    ChatRequest canonical =
                            mode.equals("plain") ? MatrixCanonicals.plainRequest() : MatrixCanonicals.toolsRequest();
                    ChatResponse upstream = mode.equals("plain") ? plainResponse : toolsResponse;
                    write(cell, "outbound.response.json", responses.encodeResponse(canonical, upstream));
                }
            }
        }

        // Per-cell legs.
        for (String dir : DIRS) {
            boolean openAiFace = dir.charAt(0) == 'o';
            boolean openAiUpstream = dir.charAt(1) == 'o';
            for (String mode : MODES) {
                Path cell = MATRIX.resolve(dir).resolve(mode);
                ChatRequest request =
                        switch (mode) {
                            case "plain" -> MatrixCanonicals.plainRequest();
                            case "tools" -> MatrixCanonicals.toolsRequest();
                            default -> MatrixCanonicals.streamRequest();
                        };
                // Requests: face inbound + upstream outbound.
                write(
                        cell,
                        "inbound.request.json",
                        WireCodec.of(openAiFace, openAi, anthropic).encodeRequest(request));
                write(
                        cell,
                        "outbound.request.json",
                        WireCodec.of(openAiUpstream, openAi, anthropic).encodeRequest(request));
                if (mode.equals("stream")) {
                    String upstream = openAiUpstream ? openAiStream : anthropicStream;
                    write(cell, "upstream.stream.sse", upstream);
                    write(cell, "outbound.stream.sse", openAiFace ? emitOpenAiSse(chunks) : emitAnthropicSse(chunks));
                } else {
                    String upstream = openAiUpstream
                            ? (mode.equals("tools") ? openAiToolsResponse : openAiPlainResponse)
                            : (mode.equals("tools") ? anthropicToolsResponse : anthropicPlainResponse);
                    write(cell, "upstream.response.json", upstream);
                    ChatResponse canonical =
                            WireCodec.of(openAiUpstream, openAi, anthropic).decodeResponse(upstream);
                    write(
                            cell,
                            "outbound.response.json",
                            WireCodec.of(openAiFace, openAi, anthropic).encodeResponse(canonical));
                }
            }
        }

        // The anthropic corpus request fixtures (byte-golden codec output).
        write(ANTHROPIC, "chat.request.json", anthropic.encodeRequest(MatrixCanonicals.toolsRequest()));
        write(ANTHROPIC, "chat.request.stream.json", anthropic.encodeRequest(MatrixCanonicals.streamRequest()));

        // Reference print for hand-authoring the anthropic corpus response + stream (the
        // codec's view of the canonical conversation — author the upstream-shaped files to
        // match). Gated behind an env flag — these
        // are authoring aids, not assertions, and they added log noise to every capture
        // run (JANUS_FIXTURE_CAPTURE_VERBOSE=1 to print).
        if ("1".equals(System.getenv("JANUS_FIXTURE_CAPTURE_VERBOSE"))) {
            System.out.println("=== anthropic encodeResponse(plain canonical) ===");
            System.out.println(anthropic.encodeResponse(plainResponse));
            System.out.println("=== anthropic stream encoder output (canonical chunks) ===");
            System.out.println(emitAnthropicSse(chunks));
        }
    }

    // ---------------------------------------------------------------- emission

    private static String emitOpenAiSse(List<StreamChunk> chunks) throws Exception {
        OpenAiMessageCodec codec = new OpenAiMessageCodec(JsonSupport.mapper());
        StringBuilder out = new StringBuilder();
        for (StreamChunk chunk : chunks) {
            out.append("data: ").append(codec.encodeChunk(chunk)).append("\n\n");
        }
        out.append("data: [DONE]"); // no trailing newline — the corpus convention
        return out.toString();
    }

    private static String emitAnthropicSse(List<StreamChunk> chunks) throws Exception {
        AnthropicStreamEncoder encoder = new AnthropicMessageCodec(JsonSupport.mapper()).newStreamEncoder();
        StringBuilder out = new StringBuilder();
        for (StreamChunk chunk : chunks) {
            for (AnthropicSseEvent event : encoder.feed(chunk)) {
                out.append("event: ").append(event.event()).append('\n');
                out.append("data: ").append(event.dataJson()).append("\n\n");
            }
        }
        for (AnthropicSseEvent event : encoder.finish()) {
            out.append("event: ").append(event.event()).append('\n');
            out.append("data: ").append(event.dataJson()).append("\n\n");
        }
        return out.toString();
    }

    // ---------------------------------------------------------------- helpers

    private static String inFile(String mode) {
        return mode.equals("stream") ? "upstream.stream.sse" : "upstream.response.json";
    }

    private static String outFile(String mode) {
        return mode.equals("stream") ? "outbound.stream.sse" : "outbound.response.json";
    }

    private static void copy(Path from, Path to) throws IOException {
        Files.createDirectories(to.getParent());
        Files.copy(from, to, java.nio.file.StandardCopyOption.REPLACE_EXISTING);
    }

    /**
     * The Responses-face inbound wire per mode (hand-authored from
     * {@link MatrixCanonicals} — the corpus pins the client bytes; the codec is
     * decode-only for requests on this face). Stream mode carries {@code stream:true}
     * only — the face's ingress decode forces {@code include_usage} (decision B).
     */
    private static String responsesInbound(String mode) {
        String base = "{\"model\":\"" + MatrixCanonicals.MODEL + "\"," + "\"instructions\":\"" + MatrixCanonicals.SYSTEM
                + "\"";
        return switch (mode) {
            case "plain" ->
                base + ",\"input\":\"" + MatrixCanonicals.USER_PROMPT + "\"," + "\"max_output_tokens\":"
                        + MatrixCanonicals.MAX_TOKENS + "}";
            case "tools" ->
                base + ",\"input\":["
                        + "{\"type\":\"message\",\"role\":\"user\",\"content\":\"" + MatrixCanonicals.USER_PROMPT
                        + "\"},"
                        + "{\"type\":\"function_call\",\"call_id\":\"call_1\",\"name\":\"get_weather\","
                        + "\"arguments\":\"{\\\"city\\\":\\\"Paris\\\"}\"},"
                        + "{\"type\":\"function_call_output\",\"call_id\":\"call_1\","
                        + "\"output\":\"{\\\"temp\\\":18}\"}],"
                        + "\"tools\":[{\"type\":\"function\",\"name\":\"get_weather\","
                        + "\"parameters\":" + MatrixCanonicals.TOOL_SCHEMA + "}],"
                        + "\"tool_choice\":\"auto\","
                        + "\"max_output_tokens\":" + MatrixCanonicals.MAX_TOKENS + "}";
            case "stream" ->
                base + ",\"input\":\"" + MatrixCanonicals.USER_PROMPT + "\"," + "\"max_output_tokens\":"
                        + MatrixCanonicals.MAX_TOKENS + ",\"stream\":true}";
            default -> throw new IllegalArgumentException(mode);
        };
    }

    private static String readResource(String path) throws IOException {
        try (InputStream in = MatrixFixtureGeneratorTest.class.getResourceAsStream(path)) {
            if (in == null) {
                throw new IOException("missing fixture resource " + path);
            }
            return new String(in.readAllBytes(), StandardCharsets.UTF_8);
        }
    }

    private static void write(Path dir, String name, String content) throws IOException {
        Files.createDirectories(dir);
        Files.writeString(dir.resolve(name), content, StandardCharsets.UTF_8);
    }
}
